### ISSUE TITLE
Installation Script or QuickStart to install and setup a default configuration

### ISSUE THREAD

**Issue by sheldonhull** [scrthq/PSProfile#12]
Consider adding an install script that can be invoked, or providing a single snippet that installs, creates your profile script if it does not exist, and adds a basic prompt config selection or template. Almost like how chocolatey is super easy to setup from scratch with one command.

I'd really like to get others to use, but suggest that having a "dummy proof" start to just run and then it's good to go would be a great way to get others not quick so involved with tinkering benefit and buy in to this. 

If I get time (unlikely in next week or so) I'll see if can create one, otherwise i'm up for testing one you create.

**Comment by scrthq** [comment]
@sheldonhull - In progress!

![image](https://user-images.githubusercontent.com/12724445/63915005-87458d00-c9fa-11e9-8f32-08a5c4c30a03.png)

**Comment by sheldonhull** [comment]
WOW. This is uber cool. What a good start!

**Comment by scrthq** [comment]
Keeping this open until it's out so I can track it appropriately =]

**Comment by scrthq** [comment]
This is now available! Give it a shot with v0.2.0 of PSProfile by running `Start-PSProfileConfigurationHelper`. I'd love your feedback on it!
