### ISSUE TITLE
How Do I use Register-EditorCommand functions to load in Visual Studio Code?

### ISSUE THREAD

**Issue by sheldonhull** [scrthq/PSProfile#2]
My current profile has a switch statement to identify Visual Studio Code profile apart from regular console and loads in a library of EditorCommands for use in visual studio such as enhanced comment headers using PSFramework, and other useful things to increase my productivity. 

How can I bootstrap these into the loading process to load all the editor commands in a folder, and only run this for Visual Studio code?

Example of my current logic: 

```powershell

#----------------------------------------------------------------------------#
#                           Host Specific Settings                           #
#----------------------------------------------------------------------------#
switch ($Host.Name)
{

    'Visual Studio Code Host'
    {
        [void]$StopWatch.Restart()
        $null = Import-Module EditorServicesCommandSuite -ErrorAction SilentlyContinue # Might error if vscode already loaded, bypassing
        Write-PSFMessage -Level Important -Message ( "{0:hh\:mm\:ss\.fff}|{1,-20}|{2,-50}" -f $StopWatch.Elapsed, 'finished', 'Import-Module EditorServicesCommandSuite'); $IncrementalElapsed += $StopWatch.Elapsed.TotalMilliseconds

        [void]$StopWatch.Restart()
        $null = Import-EditorCommand -Module EditorServicesCommandSuite
        Get-ChildItem -Path "$PSScriptRoot\vscode-editor-commands" -Recurse -Filter *.ps1 | ForEach-Object {
            .  "$($_.FullName)"
        }
        Write-PSFMessage -Level Important -Message ( "{0:hh\:mm\:ss\.fff}|{1,-20}|{2,-50}" -f $StopWatch.Elapsed, 'finished', 'Import-EditorCommand'); $IncrementalElapsed += $StopWatch.Elapsed.TotalMilliseconds
        Set-PSReadLineKeyHandler -Chord 'Ctrl+w' -Function BackwardKillWord
        Set-PSReadLineKeyHandler -Chord 'Alt+D' -Function KillWord
        Set-PSReadLineKeyHandler -Chord 'Ctrl+@' -Function MenuComplete
        #Set-PSReadLineKeyHandler -Key ([char]0x03) -Function CopyOrCancelLine
        Set-PSReadLineKeyHandler -Chord 'Ctrl+C' -Function Abort
        #Get-PSReadLineKeyHandler
        #Remove-PSReadLineKeyHandler -Key ([char]0x03)
    }
  'ConsoleHost'
    {
        #Set-Theme Fish
        #$ThemeSettings.GitSymbols.BranchSymbol = [char]::ConvertFromUtf32(0xE0A0)


        # Generate Random Session Name for windows. Doesn't really apply to vscode, but for powershell and conemu it's fun
        [void]$StopWatch.Restart()
        $local:RandomTitle = Invoke-Generate "PowerShell[space]-[space][Adjective][Noun]"
        $Host.UI.RawUI.WindowTitle = $local:RandomTitle

        Write-PSFMessage -Level Important -Message ( "{0:hh\:mm\:ss\.fff}|{1,-20}|{2,-50}" -f $StopWatch.Elapsed, 'finished', 'Invoke-Generate // random session name'); $IncrementalElapsed += $StopWatch.Elapsed.TotalMilliseconds
    'Windows PowerShell ISE Host'
    {
        [void]$StopWatch.Restart()
        Import-Module PsISEProjectExplorer -verbose:$false
        Write-PSFMessage -Level Important -Message ( "{0:hh\:mm\:ss\.fff}|{1,-20}|{2,-50}" -f $StopWatch.Elapsed, 'finished', 'Import-Module PsISEProjectExplorer'); $IncrementalElapsed += $StopWatch.Elapsed.TotalMilliseconds

        [void]$StopWatch.Restart()
        Start-Steroids
        Write-PSFMessage -Level Important -Message ( "{0:hh\:mm\:ss\.fff}|{1,-20}|{2,-50}" -f $StopWatch.Elapsed, 'finished', 'Start-Steroids'); $IncrementalElapsed += $StopWatch.Elapsed.TotalMilliseconds
    }

    }
#----------------------------------------------------------------------------#
#                       Dot Source Alternative Prompts                       #
#----------------------------------------------------------------------------#


Get-ChildItem -Path "$PSScriptRoot\prompts" -Recurse -Filter *.ps1 | ForEach-Object {
    .  "$($_.FullName)"
}

```

I then have it load some other stuff globally, like `Add-PowerLineBlock {Write-AWSPrompt} -AutoRemove` to allow quickly managing an improved prompt, along with stuff like `Terminal-Icons` etc. 

Look forward to any ideas that make this straight forward to load

**Comment by scrthq** [comment]
Hey @sheldonhull - any scripts you want to run during profile load you'll want to add to the `ScriptPaths` property on the `$PSProfile` object. Quick way to do that:

```powershell
$PSProfile.ScriptPaths += $path
Save-PSProfile
$PSProfile.Load()
```

**Comment by scrthq** [comment]
Some updates to the provided instructions using the latest version of the repo:

```powershell
Set-PSProfileSetting ScriptPaths -Add $path -Save
```

**Comment by scrthq** [comment]
Even easier on the released version: 

```powershell
Add-PSProfileScriptPath $path -Save
```

If you'd like to also immediately invoke it in your current session, include the `-Invoke` switch as well!

**Comment by sheldonhull** [comment]
Thank you I'll try this out! Sounds like things might just become easier

**Comment by sheldonhull** [comment]
Follow-up since related to this fix and trying out the improvements. 
I ran `Add-PSProfileScriptPath -Path 'C:\Users\Me\Documents\posh-profile\vscode-editor-commands' -Save` and i still get no commands. 

I also added
```powershell
Add-PSProfileModuleToImport -Name 'EditorServicesCommandSuite' -Save -MinimumVersion 0.4.0
```

with the results of: 

```powershell
WARNING: [13:27:11] '' Error importing module:
```

**Comment by scrthq** [comment]
hey @sheldonhull

**Comment by scrthq** [comment]
Regarding the inclusion in ModulesToImport and the subsequent warning; if you run `$PSProfile.ModulesToImport.Count`, do you see a higher count than actually exists? E.g.:

![image](https://user-images.githubusercontent.com/12724445/64051533-0513b080-cb41-11e9-9433-78c445a41666.png)


The latest update should resolve the empty items in the array issue from attempting to be imported, in case you haven't updated yet

**Comment by sheldonhull** [comment]
Will check next week and get back to you. Thanks!

**Comment by scrthq** [comment]
FYI - working on getting v0.2.0 out this weekend (possibly tonight maybe?), which handles the special case inclusion for `EditorServicesCommandSuite` if it's in your `$PSProfile.ModulesToImport`, including running `Import-EditorCommand -Module EditorServicesCommandSuite` as well. Just tested and it's working nicely :D

**Comment by scrthq** [comment]
@sheldonhull - v0.2.0 has been published! You should be able to simply run the following to add the module to your PSProfile.ModulesToImport, then any subsequent loads of PSProfile in Code's PSIC should have the commands present and ready to rock.

```powershell
Add-PSProfileModuleToImport EditorServicesCommandSuite -Save
```

**Comment by sheldonhull** [comment]
Wow! Looking forwarded this. I'm sorry I haven't responded as quickly as I'd like, I've been very busy with some projects at work. However this is now my new base profile, and I'm working on leveraging at piece by piece to replace my old homegrown stuff. Stuff that 1/100 as elegant as yours 😁

**Comment by scrthq** [comment]
No sweat! Let me know if you have questions or issues or anything else!

**Comment by sheldonhull** [comment]
Sorry, i might have misssed in your description. 
I get how to load editorservices command. 
However, what PSProfile function should I use to conditionally have it load the custom editor command itself? `Add-PSProfileScriptPath`? with the function?

**Comment by scrthq** [comment]
@sheldonhull - For now, you'd want to have that in an external script file whose path is added with `Add-PSProfileScriptPath`, so your thought process is correct! Working on opening a feature request to add an init script to your configuration as well =]
