### ISSUE TITLE
Bug: Sometimes PSProfile doesn't load the $PSProfile variable and things break...

### ISSUE THREAD

**Issue by corbob** [scrthq/PSProfile#23]
This has happened twice to me, and I have been unable to consistently reproduce it. A new session it doesn't happen to, but it's also only happened in a fresh session...

![image](https://user-images.githubusercontent.com/30301021/67010819-42a5ac00-f0a3-11e9-9814-e5dd04eb9968.png)

Note: PSProfile is **not** currently loaded by my profile. The 3 seconds it's taking is unrelated to PSProfile.

**Comment by scrthq** [comment]
when you hit that situation....

1. Does it show the module as imported (e.g. `$null -ne (Get-Module PSProfile)`)?
2. Do you see any difference if you force import the module after via `Import-Module PSProfile -Force`?

**Comment by scrthq** [comment]
Do you have any additional parameters added to your shortcut to launch PowerShell, e.g. `-NonInteractive`? Assuming no, but it looks like this bit from the PSM1 isn't running which creates the initial PSProfile object and loads the configuration: https://github.com/scrthq/PSProfile/blob/master/PSProfile/PSProfile.psm1

The above snippet is added to the bottom of the compiled PSM1 file when building the module.

**Comment by scrthq** [comment]
HMMM wait, line 3 on that doesn't appear to be too friendly, let me sanity check if that actually has shipped or not

**Comment by scrthq** [comment]
Hey @corbob - This shouldn't happen anymore after `0.6.0` - can you update when possible and keep me updated if it happens again? Going to close this out for now.
