### ISSUE TITLE
$PSDefaultParameterValue defined in init script not working

### ISSUE THREAD

**Issue by janegilring** [scrthq/PSProfile#26]
I have the following code defined as an init script:

```powershell
  InitScripts = @{
    Variables = @{

      ScriptBlock = '$host.PrivateData.ErrorForegroundColor = ''White''

        $PSDefaultParameterValues.Add("Send-MailMessage:To","jan.egil.ring@crayon.com")
        $PSDefaultParameterValues.Add("Update-Help:ErrorAction","SilentlyContinue")
        $PSDefaultParameterValues.Add("Test-Connection:Count","1")
        $PSDefaultParameterValues.Add("Start-SimplePomodoro:IFTTMuteTrigger","pomodoro_start")
        $PSDefaultParameterValues.Add("Start-SimplePomodoro:IFTTUnMuteTrigger","pomodoro_stop")
        $PSDefaultParameterValues.Add("Start-SimplePomodoro:IFTTWebhookKey","123")

      '
      Enabled = $True
    }
  }
```

$host.PrivateData.ErrorForegroundColor is set correctly, but $PSDefaultParameterValues is blank.

Any idea why? Or are there better approaches to setting variable values?

**Comment by scrthq** [comment]
Try changing the scope to `Global`, since these are executing from the module scope:

```powershell
  InitScripts = @{
    Variables = @{

      ScriptBlock = '$host.PrivateData.ErrorForegroundColor = ''White''

        $global:PSDefaultParameterValues.Add("Send-MailMessage:To","jan.egil.ring@crayon.com")
        $global:PSDefaultParameterValues.Add("Update-Help:ErrorAction","SilentlyContinue")
        $global:PSDefaultParameterValues.Add("Test-Connection:Count","1")
        $global:PSDefaultParameterValues.Add("Start-SimplePomodoro:IFTTMuteTrigger","pomodoro_start")
        $global:PSDefaultParameterValues.Add("Start-SimplePomodoro:IFTTUnMuteTrigger","pomodoro_stop")
        $global:PSDefaultParameterValues.Add("Start-SimplePomodoro:IFTTWebhookKey","123")

      '
      Enabled = $True
    }
  }
```

**Comment by janegilring** [comment]
Of course, that was it - thanks! 👌

**Comment by scrthq** [comment]
Sweet! No problem!

**Comment by scrthq** [comment]
Hey @janegilring - I updated the hidden `$PSProfile._globalize()` method to also "globalize" any instance of `$PSDefaultParameterValue` in an InitScript or ScriptPath, just in case you change things up down the line. PSProfile is already doing this for non-global functions in scripts so that they're surfaced to the actual session scope. New in `0.6.0` :D

**Comment by janegilring** [comment]
Very nice! 👌😃

**Comment by scrthq** [comment]
Here's the method:

https://github.com/scrthq/PSProfile/blob/master/PSProfile/Classes/PSProfile.Classes.ps1#L289..L303

Usage examples:

https://github.com/scrthq/PSProfile/blob/master/PSProfile/Classes/PSProfile.Classes.ps1#L684

https://github.com/scrthq/PSProfile/blob/master/PSProfile/Classes/PSProfile.Classes.ps1#L756
