### ISSUE TITLE
Known incompatibilities with the oh-my-posh module?

### ISSUE THREAD

**Issue by janegilring** [scrthq/PSProfile#27]
Are there any known incompatibilities between oh-my-posh and PSProfile?

When running the following script via PSProfile:

```powershell
function Test-WindowsTerminal ($id) {

  #if ($Env:WT_SESSION) {$true}
    $Process = Get-Process -Id $id
    if($null -eq $Process.Parent){return $false}
    if($Process.Name -eq 'WindowsTerminal'){return $true}

    Test-WindowsTerminal -Id $Process.Parent.Id

  }

  if (Test-WindowsTerminal $pid) {

    Write-Output 'Running in Windows Terminal'

    if (Get-Module -Name oh-my-posh -ListAvailable) {

      Import-Module -Name oh-my-posh -Scope Global
      Set-Theme -name Paradox

    }

  }
```

I get this prompt when PSProfile imports:

```powershell
cmdlet Switch-PSProfilePrompt at command pipeline position 1
Supply values for the following parameters:
Name:
```

Current workaround is to define the above code in $profile.

**Comment by scrthq** [comment]
None that I'm aware of, but I wouldn't be surprised if there was an alias conflict around some of the -Prompt aliases for the -PSProfilePrompt functions. Checking it out!

**Comment by scrthq** [comment]
Looks like `oh-my-posh` is already using `Set-Prompt` as an alias for `Switch-PSProfilePrompt` (which aligns with the error). I'm going to pull that alias from the next release, that should resolve any compatibility issues!

**Comment by janegilring** [comment]
Awesome!

**Comment by scrthq** [comment]
Update rolled out in 0.6.0 - let me know if all is well!

**Comment by janegilring** [comment]
Moved the loading of oh-my-posh from the regular profile back into a script loaded by PSProfile, and all is good now after upgrading to 0.6.0 👌

**Comment by scrthq** [comment]
Thank you so much for confirming!
