### ISSUE TITLE
$PSProfile.Refresh() clears secrets

### ISSUE THREAD

**Issue by janegilring** [scrthq/PSProfile#31]
After adding some new secrets I ran $PSProfile.Refresh() in a different PowerShell host to pick up the changes.

However, all existing secrets was cleared from the configuration file - and hence not available in any new runspaces.

Repro:

1. Add-PSProfileSecret -Save -Force ### Some dummy cred like test@domain.com
2. Check configuration file before proceeding, item test@domain.com should be present
3. $PSProfile.Refresh()
4. Check configuration file before proceeding, item test@domain.com and all other secrets is now gone
5. Get-PSProfileSecret -Name test@domain.com

**Comment by scrthq** [comment]
Alright, this makes sense! Thank you for opening this up, I've actually been seeing something similar and haven't had much luck tracking it down yet. Getting this fixed ASAP!

**Comment by scrthq** [comment]
so this one is a bit odd and I believe I have the fix, but you _should_ be able to restore access to your secrets by loading PSProfile again (easiest: `Load-PSProfile`). I'll keep you updated!

**Comment by scrthq** [comment]
Update rolled out in 0.6.0 - let me know if all is well!

**Comment by janegilring** [comment]
Tested now, secrets is preserved after calling $PSProfile.Refresh() and no other issues detected 👍

**Comment by scrthq** [comment]
Awesome!!
